apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-project-deployment
  namespace: kiii
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kiii-project
  template:
    metadata:
      labels:
        app: kiii-project
    spec:
      containers:
        - name: kiii-project
          image: stefanbatandjiev/kiii-project:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: kiii-project-config
          env:
            - name: MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: kiii-project-secret
                  key: mongo-url
