apiVersion: v1
kind: Secret
metadata:
  name: kiii-project-secret
  namespace: kiii
type: Opaque
data:
  mongo-url: bW9uZ29kYitzcnY6Ly9zdGVmYW5iYXRhbmRqaWV2OmdOcWsydU5UelhUdERQUVJAY2x1c3RlcjAuejBucjg0dy5tb25nb2RiLm5ldC9FLXNob3A/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5